version: '3.8'

services:
  db:
    container_name: pg-container-cozy
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cozy-db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_cozy_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  