version: '3.8'
services:
  app:
    build: .
    command: npm run start
    volumes:
      - .:/usr/src/app:ro
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DATABASE_USER: root
      DATABASE_PASS: root
      DATABASE_NAME: mifi_test
      DATABASE_PORT: 5432
      DATABASE_CONNECTION: postgres
    links:
      - db
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mifi_test
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"