version: "3.7"

volumes:
  kong_data: {}

networks:
 kong-net:

services:
  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    container_name: konga-prepare
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://kong:${KONG_PG_PASSWORD:-kong}@kong-database:5432/konga --password kong"
    networks:
      - kong-net
    restart: on-failure
    # links:
    #   - kong-database
    # depends_on:
    #   - kong-database
    healthcheck:
      test: ["CMD", "konga", "health"]
      interval: 10s
      timeout: 10s
      retries: 10

  konga:
    container_name: konga
    image: pantsel/konga
    restart: always
    networks:
        - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      DB_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      DB_DATABASE: konga
      NODE_ENV: development
    # depends_on:
    #   - kong-database
    ports:
      - "1337:1337"